ceph_release: hammer
clustername: ceph
fs_type: xfs
data_mount_path: /var/lib/ceph/osd/{0.clustername}-{0.osd_num}
journal_sz: 1024
default_pool_sz: 3
default_min_sz: 1
default_pg_num: 128
default_pgp_num: 128
crush_chooseleaf_type: 1
monmap_path: /tmp/{0.clustername}-monmap
ceph_cfg_path: /etc/ceph/{0.clustername}.conf
mon_keyring_path: /tmp/{0.clustername}.mon.keyring
admin_keyring_path: /etc/ceph/{0.clustername}.client.admin.keyring
mount_opst: ""
osd_weigth: "1.0"

pub_network: 192.168.124.0/24
cluster_network: 192.168.126.0/24

mons: ["ictk0103r720-7"]
rgw: ictk0103r720-7
osd:
    "ictk0103r720-7":
        storage: /dev/sdaa /dev/sdab /dev/sdac /dev/sdad /dev/sdae /dev/sdaf /dev/sdag /dev/sdah

    "ictk0103r720-8":
        storage: /dev/sdai /dev/sdaj /dev/sdak /dev/sdal /dev/sdam /dev/sdan /dev/sdao /dev/sdap /dev/sdaq

    "ictk0103r720-9":
        storage: /dev/sdar /dev/sdas /dev/sdat /dev/sdau /dev/sdav /dev/sdaw /dev/sdax /dev/sday /dev/sdaz

    "ictk0103r720-10":
        storage: /dev/sdba /dev/sdbb /dev/sdbc /dev/sdbd /dev/sdbe /dev/sdbf /dev/sdbg /dev/sdbh /dev/sdbi


# pub_network: 10.20.22.0/24
# cluster_network: 10.20.22.0/24
# mons: koder-centos-ceph0
# rgw: koder-centos-ceph0
# mons_ip: 10.20.22.149
# osd:
#     koder-centos-ceph0:
#         storage: /dev/sdb /dev/sdc /dev/sdd

#     koder-centos-ceph1:
#         storage: /dev/sdb /dev/sdc /dev/sdd

#     koder-centos-ceph2:
#         storage: /dev/sdb /dev/sdc /dev/sdd

