ceph_release: hammer
clustername: ceph
fs_type: xfs
data_mount_path: /var/lib/ceph/osd/{0.clustername}-{0.osd_num}
journal_sz: 1024
default_pool_sz: 3
default_min_sz: 1
default_pg_num: 128
default_pgp_num: 128
crush_chooseleaf_type: 1
# crush_chooseleaf_type: 0
monmap_path: /tmp/{0.clustername}-monmap
ceph_cfg_path: /etc/ceph/{0.clustername}.conf
mon_keyring_path: /tmp/{0.clustername}.mon.keyring
admin_keyring_path: /etc/ceph/{0.clustername}.client.admin.keyring
mount_opst: ""
osd_weigth: "1.0"
pub_network: 192.168.152.0/24
cluster_network: 192.168.152.0/24

mons: ['ceph-mon']
# rgw: ictk0103r720-7
osd:
    "ceph-osd-0":
        storage: /dev/sdb

    "ceph-osd-1":
        storage: /dev/sdb

    "ceph-osd-2":
        storage: /dev/sdb
